# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Moments
    url: moments
    weight: 20
  - name: Experiences
    url: experiences/
    weight: 30

